--- 
- 
  hosts: all
  name: "sample Tower Program"
  tasks: 
    - 
      command: "touch /root/tower"
      name: "File Creation"
      resister: file
    - 
      debug: "msg={{ file.stdout }}"
      
