---
- 
  name: "sample Tower Program"
  hosts: all
  tasks:
    - 
      command: "touch /root/tower"
      name: "File Creation"
    - debug:
         msg: "File Created"
~                                                                               
~                 
